# Generated by Django 3.0.8 on 2020-07-26 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0002_auto_20200725_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Numero_Documento', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=0)),
                ('Fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Cliente')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Factura',
            field=models.ManyToManyField(through='cajero.Factura', to='almacen.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Tipo_Documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Documento'),
        ),
    ]
