# Generated by Django 3.1.1 on 2020-09-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmodel', '0002_carmodel_updated'),
        ('cartype', '0001_initial'),
        ('carbrand', '0004_auto_20200906_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.IntegerField()),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbrand.brand')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmodel.carmodel')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartype.cartype')),
            ],
        ),
    ]
