# Generated by Django 3.0.8 on 2020-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=200)),
                ('fechaFact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
