# Generated by Django 3.0.8 on 2020-07-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='producto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
