# Generated by Django 3.0.8 on 2020-07-27 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_comprobantepago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipodoc', models.CharField(max_length=1)),
                ('nro_tipodoc', models.CharField(max_length=8)),
                ('igv', models.FloatField(default=0.18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dni', models.IntegerField(max_length=8)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Det_comprobantepago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabcomprobantepago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Cab_comprobantepago')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='cab_comprobantepago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Cliente'),
        ),
    ]
