# Generated by Django 3.0.8 on 2020-07-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='descripcione',
            new_name='descripcion',
        ),
    ]
