# Generated by Django 3.1 on 2020-09-02 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opt_payment', models.CharField(choices=[(1, 'cash'), (2, 'card'), (3, 'credit card')], max_length=20)),
                ('usr_id', models.CharField(max_length=20)),
                ('usr_point', models.CharField(choices=[(1, 'yes'), (0, 'no')], max_length=5)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
