# Generated by Django 3.0.8 on 2020-07-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=200)),
                ('dniCliente', models.CharField(max_length=8)),
                ('direccionCliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rucEmpresa', models.CharField(max_length=11)),
                ('direccionEmpresa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFacturaCabecera', models.DateTimeField()),
                ('igvFacturaCabecera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotalFacturaCabecera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalFacturaCabecera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoFactura', models.CharField(max_length=20)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Cliente')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='facturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantFactDetalle', models.IntegerField(default=0)),
                ('valorFactDetalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFacturaCabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.FacturaCabecera')),
                ('idProductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Producto')),
            ],
        ),
    ]
