"""empty message

Revision ID: 1f2d54e0a3c2
Revises: 
Create Date: 2020-08-06 10:42:32.855984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d54e0a3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreCategoria', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombreCategoria'), 'categoria', ['nombreCategoria'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreCliente', sa.String(length=100), nullable=True),
    sa.Column('dniCliente', sa.String(length=100), nullable=True),
    sa.Column('direcccionCliente', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_direcccionCliente'), 'cliente', ['direcccionCliente'], unique=False)
    op.create_index(op.f('ix_cliente_dniCliente'), 'cliente', ['dniCliente'], unique=False)
    op.create_index(op.f('ix_cliente_nombreCliente'), 'cliente', ['nombreCliente'], unique=False)
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreEmpresa', sa.String(length=100), nullable=True),
    sa.Column('direcccionEmpresa', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_direcccionEmpresa'), 'empresa', ['direcccionEmpresa'], unique=False)
    op.create_index(op.f('ix_empresa_nombreEmpresa'), 'empresa', ['nombreEmpresa'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('venta_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura_cabecera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igvTotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreProducto', sa.String(length=100), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_nombreProducto'), 'producto', ['nombreProducto'], unique=False)
    op.create_table('factura_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('facturacabecera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facturacabecera_id'], ['factura_cabecera.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura_detalle')
    op.drop_index(op.f('ix_producto_nombreProducto'), table_name='producto')
    op.drop_table('producto')
    op.drop_table('factura_cabecera')
    op.drop_table('venta_diaria')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_empresa_nombreEmpresa'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_direcccionEmpresa'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_index(op.f('ix_cliente_nombreCliente'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_dniCliente'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_direcccionCliente'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_categoria_nombreCategoria'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
