# Generated by Django 3.1 on 2020-08-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=15)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdds.tipodocumentos')),
            ],
        ),
    ]
