# Generated by Django 3.1 on 2020-08-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0002_transportista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transportista',
            new_name='transportistas',
        ),
    ]
