# Generated by Django 3.1 on 2020-08-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0004_clientes_detallepedido_pedidos_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='cliente',
        ),
        migrations.RenameModel(
            old_name='pedidos',
            new_name='pedido',
        ),
        migrations.RenameModel(
            old_name='productos',
            new_name='producto',
        ),
        migrations.RenameModel(
            old_name='tipoProductos',
            new_name='tipoCliente',
        ),
        migrations.RenameModel(
            old_name='tipoClientes',
            new_name='tipoDocumento',
        ),
        migrations.RenameModel(
            old_name='tipoDocumentos',
            new_name='tipoProducto',
        ),
        migrations.RenameModel(
            old_name='transportistas',
            new_name='transportista',
        ),
    ]
