# Generated by Django 3.1 on 2020-08-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0007_auto_20200817_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Recibido', max_length=30),
        ),
    ]
