# Generated by Django 3.1 on 2020-08-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0008_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
