# Generated by Django 3.1 on 2020-08-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdds', '0009_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
