# Generated by Django 3.1 on 2020-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='isGenerico',
            field=models.BooleanField(choices=[(True, 'GENERICO'), (False, 'COMERCIAL')], default=True),
        ),
    ]
