# Generated by Django 3.1 on 2020-08-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma', '0002_auto_20200829_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredienteActivo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
