# Generated by Django 3.1.1 on 2020-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('interior', models.CharField(choices=[(1, 'standard'), (2, 'full')], max_length=20)),
            ],
        ),
    ]
