# Generated by Django 3.1.1 on 2020-09-06 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
