# Generated by Django 3.0.8 on 2020-07-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidado_actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Factura')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Periodo')),
                ('id_transsaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Transaccion')),
            ],
        ),
    ]
