-- MySQL Script generated by MySQL Workbench
-- Sun Jun 28 22:11:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dgarcia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dgarcia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dgarcia` DEFAULT CHARACTER SET utf8 ;
USE `dgarcia` ;

-- -----------------------------------------------------
-- Table `dgarcia`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`alumno` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `nombreAlumno` VARCHAR(100) NOT NULL,
  `edadAlumno` INT NOT NULL,
  `correoAlumno` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dgarcia`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`profesor` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `nombreProfesor` VARCHAR(45) NOT NULL,
  `edadProfeor` VARCHAR(45) NOT NULL,
  `correoProfesor` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dgarcia`.`semestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`semestre` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`semestre` (
  `idSemestre` INT NOT NULL AUTO_INCREMENT,
  `descSemestre` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dgarcia`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`curso` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombreCurso` VARCHAR(45) NOT NULL,
  `idProfesor` INT NOT NULL,
  `idSemestre` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_curso_profesor_idx` (`idProfesor` ASC) VISIBLE,
  INDEX `fk_curso_semestre1_idx` (`idSemestre` ASC) VISIBLE,
  CONSTRAINT `fk_curso_profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `dgarcia`.`profesor` (`idProfesor`),
  CONSTRAINT `fk_curso_semestre1`
    FOREIGN KEY (`idSemestre`)
    REFERENCES `dgarcia`.`semestre` (`idSemestre`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dgarcia`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`notas` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`notas` (
  `idNotas` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `descNota` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idNotas`),
  INDEX `fk_notas_alumno1_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `fk_notas_curso1_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_notas_alumno1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `dgarcia`.`alumno` (`idAlumno`),
  CONSTRAINT `fk_notas_curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dgarcia`.`curso` (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dgarcia`.`salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dgarcia`.`salon` ;

CREATE TABLE IF NOT EXISTS `dgarcia`.`salon` (
  `idsalon` INT NOT NULL AUTO_INCREMENT,
  `nombreSalron` VARCHAR(45) NOT NULL,
  `idAlumno` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idsalon`),
  INDEX `fk_salon_alumno1_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `fk_salon_profesor1_idx` (`idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_salon_alumno1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `dgarcia`.`alumno` (`idAlumno`),
  CONSTRAINT `fk_salon_profesor1`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `dgarcia`.`profesor` (`idProfesor`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
