# Generated by Django 3.0.8 on 2020-07-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Stock', models.IntegerField(default=0)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Categoria')),
            ],
        ),
    ]
