# Generated by Django 3.1 on 2020-09-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Auto',
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'auto', 'verbose_name_plural': 'autos'},
        ),
    ]
