# Generated by Django 3.0.8 on 2020-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDiaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
