# Generated by Django 3.1 on 2020-09-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tipoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nplaca', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('km', models.IntegerField()),
                ('combustible', models.CharField(max_length=200)),
                ('motor', models.IntegerField()),
                ('nropuertas', models.IntegerField()),
                ('tapiceria', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActivo', models.CharField(choices=[('AC', 'Activo'), ('IA', 'Inactivo')], default='AC', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.modelo')),
                ('tipoAuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tipoauto')),
            ],
        ),
    ]
