# Generated by Django 3.0.8 on 2020-07-27 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcione', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IGV', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Detalle_factura')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajero.Metodo_pago')),
            ],
        ),
    ]
