--POSTGRE
--TABLA ALUMNO
CREATE TABLE public."Alumno"
(
    id_alumno integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    dni_alumno character varying(8) COLLATE pg_catalog."default",
    nombre_alumno character varying(50) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    correo_alumno character varying(50) COLLATE pg_catalog."default",
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    CONSTRAINT "Alumno_pkey" PRIMARY KEY (id_alumno),
    CONSTRAINT "Alumno_dni_key" UNIQUE (dni_alumno)
)

TABLESPACE pg_default;

ALTER TABLE public."Alumno"
    OWNER to postgres;

--TABLA SALON
CREATE TABLE public."Salon"
(
    id_salon integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    nombre_salon character varying(50) COLLATE pg_catalog."default",
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    id_bimestre integer,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    id_profesores integer,
    CONSTRAINT "Salon_pkey" PRIMARY KEY (id_salon),
    CONSTRAINT "Salon_nombre_salon_key" UNIQUE (nombre_salon),
    CONSTRAINT fk_bim FOREIGN KEY (id_bimestre)
        REFERENCES public."Bimestre" (id_bimestre) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Salon"
    OWNER to postgres;

--TABLA CURSOS
CREATE TABLE public."Cursos"
(
    id_cursos integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    nombre_curso character varying(50) COLLATE pg_catalog."default",
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    CONSTRAINT "Cursos_pkey" PRIMARY KEY (id_cursos),
    CONSTRAINT "Cursos_nombre_curso_key" UNIQUE (nombre_curso)
)

TABLESPACE pg_default;

ALTER TABLE public."Cursos"
    OWNER to postgres;

--TABLA PROFESORES
CREATE TABLE public."Profesores"
(
    id_profesores integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    nombre_profesor character varying(50) COLLATE pg_catalog."default",
    dni_profesor character varying(8) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    correo_profesor character varying(50) COLLATE pg_catalog."default",
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    CONSTRAINT "Profesores_pkey" PRIMARY KEY (id_profesores),
    CONSTRAINT "Profesores_dni_profesor_key" UNIQUE (dni_profesor)
)

TABLESPACE pg_default;

ALTER TABLE public."Profesores"
    OWNER to postgres;

--TABLA BIMESTRE
CREATE TABLE public."Bimestre"
(
    id_bimestre integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    des_bimestre character varying(50) COLLATE pg_catalog."default",
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    CONSTRAINT "Bimestre_pkey" PRIMARY KEY (id_bimestre),
    CONSTRAINT des UNIQUE (des_bimestre)
)

TABLESPACE pg_default;

ALTER TABLE public."Bimestre"
    OWNER to postgres;

--TABLA DETALLE DE LOS CURSOS CON LOS PROFESORES
CREATE TABLE public."Detalle_curpro"
(
    id_detallecurpro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    id_curso integer,
    id_profesor integer,
    CONSTRAINT "Detalle_curpro_pkey" PRIMARY KEY (id_detallecurpro),
    CONSTRAINT fk_cur FOREIGN KEY (id_curso)
        REFERENCES public."Cursos" (id_cursos) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID,
    CONSTRAINT fk_pro FOREIGN KEY (id_profesor)
        REFERENCES public."Profesores" (id_profesores) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Detalle_curpro"
    OWNER to postgres;

--TABLA DETALLE DEL ALUMNO Y EL SALON (NOTAS)
CREATE TABLE public."Detalle_alusal"
(
    id_detallealusal integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 100000 CACHE 1 ),
    nota integer,
    fecha_registro date,
    fecha_modificacion date,
    fecha_baja date,
    estado character varying(2) COLLATE pg_catalog."default" DEFAULT 1,
    id_alumno integer,
    id_salon integer,
    CONSTRAINT "Detalle_alusal_pkey" PRIMARY KEY (id_detallealusal),
    CONSTRAINT fk_alu FOREIGN KEY (id_alumno)
        REFERENCES public."Alumno" (id_alumno) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID,
    CONSTRAINT fk_sal FOREIGN KEY (id_salon)
        REFERENCES public."Salon" (id_salon) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public."Detalle_alusal"
    OWNER to postgres;
