--POSTGRE
--MODIFICACION TABLA BIMESTRE

-- MODIFICACION TABLA PROFESORES

--MODIFICANDO TABLA SALON

--MODIFICACION TABLA CURSOS

--MODIFICACION TABLA DETALLE CURSO Y PROFESORES

--MODIFICACION TABLA ALUMNO

--MODIFICAR TABLA DETALLE ALUMNO SALON (NOTAS)