# Generated by Django 3.0.8 on 2020-07-27 02:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('montoTotal', models.FloatField(default=0)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Factura')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Productos')),
            ],
        ),
    ]
