# Generated by Django 3.1.1 on 2020-09-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_Lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.album')),
                ('Artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=50)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CancionPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.cancion')),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='Artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.artista'),
        ),
    ]
