# Generated by Django 3.1 on 2020-08-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.BooleanField(default=False)),
                ('Passport', models.BooleanField(default=False)),
                ('immigrationCard', models.BooleanField(default=False)),
                ('RUC', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
                ('clientDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.document')),
                ('clientStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.status')),
            ],
        ),
    ]
