# Generated by Django 3.1 on 2020-08-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toiletries', models.BooleanField(default=False)),
                ('vitamins', models.BooleanField(default=False)),
                ('syrup', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('forbaby', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('productStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casher.stock')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casher.category')),
            ],
        ),
    ]
