# Generated by Django 3.1.1 on 2020-09-06 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
