# Generated by Django 3.1.1 on 2020-09-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0002_brand_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='updated',
            new_name='updatfed',
        ),
    ]
