# Generated by Django 3.1.1 on 2020-09-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbrand', '0003_auto_20200906_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='updatfed',
            new_name='updated',
        ),
    ]
